apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo-cm
data:
  index.html: >-
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Custom Nginx Page</title>
    </head>
    <body>
        <h1> Welcome to ITP Devops </h1>
        <p> This is the customized page of nginx page </p>
    </body>
    </html>
  # error-page: |
  #  <h1> THis is just an error page </h1>