apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-dpl
spec:
  selector:
    matchLabels:
      app: nginx-demo-app
  template:
    metadata:
      labels:
        app: nginx-demo-app
    spec:
      containers:
      - name: nginx-demo-app
        image: nginx:alpine 

        ports:
        - containerPort: 80 
        volumeMounts: 
          - name: config-demo
            mountPath: /usr/share/nginx
      volumes: 
        - name: config-demo 
          configMap: 
            name: nginx-demo-cm 
            items: 
              - key: index.html 
                path: html/index.html      