apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-based-ingress
  #labels:
  #  app.kubernetes.io/name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingressClassName: "nginx"
spec:
  ingressClassName: "nginx"
  tls: 
    - hosts: 
      - nginx-demo-k8s.anajak-khmer.site
      #- reactjs-demo-k8s.anajak-khmer.site
      secretName: nginx-k8s-tls 
  rules:
  - host: nginx-demo-k8s.anajak-khmer.site 
    http:
      paths:
      - pathType: Prefix
        path: "/nginx"
        backend:
          service:
            name: nginx-svc 
            port: 
              number: 80 
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: earthdx-svc 
            port: 
              number: 80 
