apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-demo
spec:
  selector:
    matchLabels:
      app: my-app-demo
  template:
    metadata:
      labels:
        app: my-app-demo
    spec:
      containers:
      - name: my-app-demo
        image: nginx:latest
        ports:
        - containerPort: 80
